import React from 'react'
import styles from '../styles/Blog.module.css'
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'

export default function Blog(props) {
  const [blog, setblog] = useState(props.data)
  return (
    <div>
         <Head>
        <title>Hunting Coder : Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <main className={styles.main}>
        <div className={styles.mar}>
            {blog.map((elem)=>{
              return  <a key={elem.slug}>
              <Link href={`/blog/${elem.slug}`} >
                <h2 className={styles.title}>{elem.title} &rarr;</h2></Link>
                <p className={styles.para}>{elem.description}</p>
                <hr/>
                </a>
            })}
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const url = "http://localhost:3000/api/blogs";
  let response = await fetch(url);
  let data = await response.json();
  return {
    props: {data}
  }
}
