import React from 'react'
import styles from '../styles/Contact.module.css'
import Head from 'next/head'
import { useState } from 'react'

export default function Contact() {
  const [name, setname] = useState("")
  const [phone, setphone] = useState("")
  const [email, setemail] = useState("")
  const [desc, setdesc] = useState("")
  const handleSubmit = async (e)=>{
    e.preventDefault();
    await fetch("http://localhost:3000/api/contactData", {
      method: 'POST',
      mode: 'cors',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({name,email,phone,desc})
    });
    setname("");
    setemail("");
    setphone("");
    setdesc("");
  }

  const handleChange = (e)=>{
    if(e.target.name==="name")setname(e.target.value);
    if(e.target.name==="phone")setphone(e.target.value);
    if(e.target.name==="email")setemail(e.target.value);
    if(e.target.name==="desc")setdesc(e.target.value);
  }
  return (
    <div>
         <Head>
        <title>Hunting Coder : Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>
        {`
        .container{
          display:flex;
          justify-content:center;
          margin-bottom: 12rem;

        }
        `}
      </style>
      <h1 className={styles.main}>Contact Us</h1>
<div className="container">
        <form onSubmit={handleSubmit} className={styles.form}>
          <label htmlFor="name">Name</label>
          <input type="text" name="name" id="name" style={{marginBottom:"2px"}} value={name} onChange={handleChange} />
          <label htmlFor="email">Email</label>
          <input type="email" name="email" id="email" value={email} style={{marginBottom:"2px"}} onChange={handleChange} />
          <label htmlFor="phone">Phone</label>
          <input type="phone" name="phone" id="phone" value={phone} style={{marginBottom:"2px"}} onChange={handleChange} />
          <label htmlFor="desc">Description</label>
          <textarea type="textarea" name="desc" id="desc" value={desc} style={{marginBottom:"2px"}} onChange={handleChange} />
          <button type="submit" style={{marginTop:"8px"}}>Send</button>
        </form>
        </div>
    </div>
  )
}
